### ISSUE TITLE
Arming not working HITL in Python example

### ISSUE THREAD

**Issue by julianoes** [Dronecode/DronecodeSDK#727]
It seems like we can't arm (or we can't arm immediately) in HITL simulation due to the error `COMMAND_DENIED_LANDED_STATE_UNKNOWN`.

The question is if it's a timing issue or if our request to send `EXTENDED_SYS_STATE` at 1 Hz fails or is not supported.

FYI @JonasVautherin 

This works with C++ but seems to fail with this Python example:
```
#!/usr/bin/env python3

import asyncio

from dronecode_sdk import connect as dronecode_sdk_connect
from dronecode_sdk import start_mavlink

start_mavlink()
drone = dronecode_sdk_connect(host="127.0.0.1")


async def run():
    print("-- Arming")
    await drone.action.arm()
    print("-- Taking off")
    await drone.action.takeoff()
    await asyncio.sleep(5)
    print("-- Landing")
    await drone.action.land()

loop = asyncio.get_event_loop()
loop.run_until_complete(run())

```

**Comment by julianoes** [comment]
I can reproduce the problem:
```
python3 takeoff_and_land.py 
-- Arming
Traceback (most recent call last):
  File "takeoff_and_land.py", line 21, in <module>
    loop.run_until_complete(run())
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "takeoff_and_land.py", line 13, in run
    await drone.action.arm()
  File "/home/julianoes/.local/lib/python3.7/site-packages/dronecode_sdk/plugins/action.py", line 167, in arm
    raise ActionError(result, "arm()")
dronecode_sdk.plugins.action.ActionError: COMMAND_DENIED_LANDED_STATE_UNKNOWN: 'Command denied, landed state is unknown'; origin: arm(); params: ()
```

**Comment by julianoes** [comment]
`time.sleep(3)` before arming does not seem to help.

**Comment by julianoes** [comment]
Presumably the problem is that we have no connection in HITL because we're connecting to UDP port 14540 by default but for HITL we need to use 14550.

**Comment by julianoes** [comment]
This issue is already tracked in #587!
